// Package lists embeds the built-in server list.
package lists

import _ "embed"

// BuiltinJSON is lists/servers.json, generated by tools/genservers.
//
//go:embed servers.json
var BuiltinJSON []byte
